export const DUMMY = [
        {
            projectId: 1,
            projectName: "AWH",
            deptId: 1,
            deptName: "PSO",
            startDate: "07-01-2018",
            endDate: "07-16-2018",
            totalHrs: 6,
            projectTypeId: 4,
            projectTypeDesc: "Billable",
            projectManagerId: 1,
            projectManagerName: "Robin"
        },
        {
            projectId: 2,
            projectName: "RMI",
            deptId: 1,
            deptName: "PSO",
            startDate: "07-02-2018",
            endDate: "07-15-2018",
            totalHrs: 6,
            projectTypeId: 4,
            projectTypeDesc: "Billable",
            projectManagerId: 1,
            projectManagerName: "Robin"
        },
        {
            projectId: 3,
            projectName: "LMS",
            deptId: 1,
            deptName: "PSO",
            startDate: "07-03-2018",
            endDate: "07-14-2018",
            totalHrs: 6,
            projectTypeId: 4,
            projectTypeDesc: "Non-Billable",
            projectManagerId: 1,
            projectManagerName: "Robin"
        },
        {
            projectId: 4,
            projectName: "Timesheet",
            deptId: 1,
            deptName: "PSO",
            startDate: "07-04-2018",
            endDate: "07-10-2018",
            totalHrs: 6,
            projectTypeId: 4,
            projectTypeDesc: "Non-Billable",
            projectManagerId: 1,
            projectManagerName: "Robin"
        },
        {
            projectId: 5,
            projectName: "Resource Allocation",
            deptId: 1,
            deptName: "PSO",
            startDate: "07-05-2018",
            endDate: "07-15-2018",
            totalHrs: 6,
            projectTypeId: 4,
            projectTypeDesc: "Non-Billable",
            projectManagerId: 1,
            projectManagerName: "Robin"
        },
        {
            projectId: 6,
            projectName: "Video",
            deptId: 1,
            deptName: "PSO",
            startDate: "07-06-2018",
            endDate: "07-11-2018",
            totalHrs: 6,
            projectTypeId: 4,
            projectTypeDesc: "Non-Billable",
            projectManagerId: 1,
            projectManagerName: "Robin"
        },
        {
            projectId: 7,
            projectName: "Resource Allocation",
            deptId: 1,
            deptName: "PSO",
            startDate: "07-07-2018",
            endDate: "07-18-2018",
            totalHrs: 6,
            projectTypeId: 4,
            projectTypeDesc: "Non-Billable",
            projectManagerId: 1,
            projectManagerName: "Robin"
        },
        {
            projectId: 8,
            projectName: "Video",
            deptId: 1,
            deptName: "PSO",
            startDate: "07-08-2018",
            endDate: "07-19-2018",
            totalHrs: 6,
            projectTypeId: 4,
            projectTypeDesc: "Non-Billable",
            projectManagerId: 1,
            projectManagerName: "Robin"
        }
    ]
 