export const PROFILEDUMMY = [
    {
        resourceId: 1,
        name: "Saquib",
        email:"",
        startDate: "06-28-2017",
        endDate: "06-30-2018",
        contact:"",
        deptId: 1,
        deptName: "PSO",
        resourceTypeId:"",
        resourceTypeDesc:"",
        roleId:"",
        roleDesc:"",
        locationId:"",
        locationName:"",
        isActive:"",
        managerId:"",
        managerName:"Robin",
        designation: "Software Developer",
        location:"Lucknow, India",
        projects: ["RMI", "AAParser", "Resource Allocation"]
    },
    {
        resourceId: 2,
        name: "Ayushi",
        email:"",
        startDate: "28-06-2017",
        endDate: "28-06-2018",
        contact:"",
        deptId: 1,
        deptName: "PSO",
        resourceTypeId:"",
        resourceTypeDesc:"",
        roleId:"",
        roleDesc:"",
        locationId:"",
        locationName:"",
        isActive:"",
        managerId:"",
        managerName:"Robin",
        designation: "Software Developer",
        location:"Lucknow, India",
        projects: ["RMI", "AAParser", "Resource Allocation"]
    }, {
        resourceId: 3,
        name: "Deepak",
        email:"",
        startDate: "28-06-2017",
        endDate: "28-06-2018",
        contact:"",
        deptId: 1,
        deptName: "PSO",
        resourceTypeId:"",
        resourceTypeDesc:"",
        roleId:"",
        roleDesc:"",
        locationId:"",
        locationName:"",
        isActive:"",
        managerId:"",
        managerName:"Robin",
        designation: "Software Developer",
        location:"Lucknow, India",
        projects: ["RMI", "AAParser", "Resource Allocation"]
    }, {
        resourceId: 4,
        name: "Salman",
        email:"",
        startDate: "28-06-2017",
        endDate: "28-06-2018",
        contact:"",
        deptId: 1,
        deptName: "PSO",
        resourceTypeId:"",
        resourceTypeDesc:"",
        roleId:"",
        roleDesc:"",
        locationId:"",
        locationName:"",
        isActive:"",
        managerId:"",
        managerName:"Robin",
        designation: "Software Developer",
        location:"Lucknow, India",
        projects: ["RMI", "AAParser", "Resource Allocation"]
    }, {
        resourceId: 5,
        name: "Gionna",
        email:"",
        startDate: "28-06-2017",
        endDate: "28-06-2018",
        contact:"",
        deptId: 1,
        deptName: "PSO",
        resourceTypeId:"",
        resourceTypeDesc:"",
        roleId:"",
        roleDesc:"",
        locationId:"",
        locationName:"",
        isActive:"",
        managerId:"",
        managerName:"Robin",
        designation: "Software Developer",
        location:"Lucknow, India",
        projects: ["RMI", "AAParser", "Resource Allocation"]
    }, {
        resourceId: 6,
        name: "Robin",
        email:"",
        startDate: "28-06-2017",
        endDate: "28-06-2018",
        contact:"",
        deptId: 1,
        deptName: "PSO",
        resourceTypeId:"",
        resourceTypeDesc:"",
        roleId:"",
        roleDesc:"",
        locationId:"",
        locationName:"",
        isActive:"",
        managerId:"",
        managerName:"Mahesh",
        designation: "Software Developer",
        location:"Lucknow, India",
        projects: ["RMI", "AAParser", "Resource Allocation"]
    }, {
        resourceId: 7,
        name: "Shivangi",
        email:"",
        startDate: "28-06-2017",
        endDate: "28-06-2018",
        contact:"",
        deptId: 1,
        deptName: "PSO",
        resourceTypeId:"",
        resourceTypeDesc:"",
        roleId:"",
        roleDesc:"",
        locationId:"",
        locationName:"",
        isActive:"",
        managerId:"",
        managerName:"Robin",
        designation: "Software Developer",
        location:"Lucknow, India",
        projects: ["RMI", "AAParser", "Resource Allocation"]
    },  {
        resourceId: 8,
        name: "Prabhjit",
        email:"",
        startDate: "28-06-2017",
        endDate: "28-06-2018",
        contact:"",
        deptId: 1,
        deptName: "PSO",
        resourceTypeId:"",
        resourceTypeDesc:"",
        roleId:"",
        roleDesc:"",
        locationId:"",
        locationName:"",
        isActive:"",
        managerId:"",
        managerName:"Robin",
        designation: "Software Developer",
        location:"Lucknow, India",
        projects: ["RMI", "AAParser"]
    }

]